require 'xcode/shell'
require 'xcode/provisioning_profile'
require 'xcode/test/parsers/ocunit_parser.rb'
require 'xcode/deploy/testflight'
require 'xcode/deploy/web'
require 'xcode/builder/base_builder.rb'
require 'xcode/builder/project_target_config_builder.rb'
require 'xcode/builder/scheme_builder.rb'