require 'xcode/shell'
require 'xcode/provisioning_profile'
require 'xcode/test/parsers/ocunit_parser.rb'
require 'xcode/testflight'
require 'xcode/builder/base_builder.rb'
require 'xcode/builder/project_target_config_builder.rb'
require 'xcode/builder/project_scheme_builder.rb'
# require 'xcode/builder/workspace_scheme_builder.rb'